import "@/css/base.css";
import "@/css/globals.css";
import "@/css/layout.css";
import "@/css/header.css";
import "@/css/hero.css";
import "@/css/main.css";
import "@/css/footer.css";
import "@/css/shortcodes.css";
import "@/css/components.css";
import "@/css/iconly.css";
import "@/css/responsive.css";
import Header from "@/parts/header/Header";
import Footer from "@/parts/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
